### ISSUE TITLE
print toctree on second page?

### ISSUE THREAD

**Issue by sonicnkt** [Nekmo/sphinx-business-theme#8]
Hi,
i stumbled upon your theme while looking for a way to easily creating some pdf documentation that is styled as the html ones.
I really love your theme but i was wondering if it was possible to print the toctree on the second page? 
I looked around a bit and found out this is related to the singlehtml output method (https://github.com/sphinx-doc/sphinx/issues/2589) 

My sphinx knowledge is quite limited, do you think there is a way to get a TOC for the whole document?
For my current purpose i am able to ditch toctree alltogether and just write the whole documentation into a single rst but it would be nice to have.

Any idea if this is possible?

**Comment by Nekmo** [comment]
Hi @sonicnkt ,

In the [demo](https://github.com/Nekmo/sphinx-business-theme/releases/latest/download/demo.pdf) there is an example of toctree. It is not on the second page but you can modify the theme.

What exactly do you need?

**Comment by sonicnkt** [comment]
The toc on the third page of the demo is generated using `.. content::` but this only generates a toc of that rst document.
For example in your demo there are several documents added to the toctree (index.rst):
```rst
.. toctree::
    :maxdepth: 2
    :numbered:
    :caption: Demo Documentation

    demo/structure
    demo/demo
    demo/lists_tables
    demo/api
    rest_api
``` 

The `.. content:: ` is the toc of `demo/structure` only. I was looking for a way to get a toc of the whole thing (strucute, demo, list_tables, etc.). This seems to be a limitation of singlehtml like i linked above. I was just wondering if there is a workaround?

My current solution is to just ditch toctree and just use a single rst (index) file and then use `.. content::` but for larger documents splitting the content into several files is better practice

**Comment by Nekmo** [comment]
@sonicnkt maybe what you need is this directive to build the index:

http://fnch.users.sourceforge.net/sphinxindexinsinglehtml.html

Try and tell me if it works for you :)

**Comment by sonicnkt** [comment]
@Nekmo thanks for the link, had to update one import from the extension to get it to work on the latest sphinx 
```
from sphinx.util.compat import Directive
```
to
```
from docutils.parsers.rst import Directive
```

But now it adds a toc to the second page when i add `.. globalindex:: ` rigfht before `.. toctree::`, it lacks the great styling tho that you applied to `.. content:: `

I also just noticed that there was a toctree all the time but a the bottom of the html... Now im wondering how to get rid of this one :D  i guess i have to learn a bit more about the sphinx rendering basics...

**Comment by Nekmo** [comment]
You are welcome :)
